### ISSUE TITLE
[PE-D][Tester D] Duplicating Contacts through Editing a Contact

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-2/tp#206] opened 2024-11-08 17:26 UTC
![Screenshot 2024-11-08 at 3.35.16 PM.png](https://raw.githubusercontent.com/samuelthen/ped/main/files/52dda6e4-7ff5-4b7c-b6cf-e96afcf15299.png)

Although it is not allowed during add command, making a duplicated contact could still be possible with the editing command.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: samuelthen/ped#2

**Comment by AgentHagu** [comment] 2024-11-09 06:16
Duplicate of #254 and side effect of #259

**Closed** 2024-11-09 15:28 UTC
Labels: type.DuplicateIssue
